version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: profashion_app
        volumes:
            - .:/var/www
        depends_on:
            - mysql
        networks:
            - profashion

    nginx:
        image: nginx:stable
        container_name: profashion_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - profashion

    mysql:
        image: mysql:8.0
        container_name: profashion_mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - profashion

volumes:
    mysql_data:

networks:
    profashion:
        driver: bridge
